### ISSUE TITLE
Filter messages from Kafka topic based on header value

### ISSUE THREAD

**Issue by harishanandan124** [ibm-messaging/kafka-connect-mq-sink#25]
Hi All,

Is there any way we can filter incoming messages from a topic based on its header field value? I tried writing transformations but none of them worked. Also, I do not see a configuration for 'filter'  option in the list of config options provided. Has anyone tried it before?

**Comment by AndrewJSchofield** [comment]
Hi, you could write a single-message transform and configure the connector to use that. Because the SMT technology exists, I personally wouldn't want to put filtering directly in the connector.

A good, general-purpose filtering SMT would be quite complicated. A simpler one with just a single purpose in mind would be fairly simple, but you will need to understand quite a bit about how Kafka Connect works to do it.

**Comment by AndrewJSchofield** [comment]
Closing dormant issue
